### ISSUE TITLE
Electoral API System Settings

### ISSUE THREAD

**Issue by d0325mgray** [josephlacey/com.jlacey.electoral#13] opened 2019-07-23 16:02 UTC
I left all the fields blank hoping that I would be able to run against all states but I got this error:

`Country Districts with result: Failure, Error message: DB Error: syntax error`

It looks like I will have to specify all the states. Do I need to do that for counties and cities too? Yuck.

**Comment by josephlacey** [comment] 2019-07-23 16:04
This is a duplicate of #10.

**Closed by josephlacey** 2019-07-23 16:04 UTC

**Comment by d0325mgray** [comment] 2019-07-23 16:15
Okay. I missed that because it was closed. I guess I missed the email too
